version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in this directory
    directory: "/source/image-handler/"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
    groups:
      npm:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "terraform"
    directory: "/source/image-handler/terraform"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
    groups:
      terraform-image-handler:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
