version: 2

updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in this directory
    directory: "/source/image-handler/"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"

  - package-ecosystem: "terraform"
    directory: "/source/image-handler/terraform"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"

  - package-ecosystem: "terraform"
    directory: "/source/thumbs/terraform"
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    # Look `Cargo.toml` in the repository root
    directory: "/source/thumbs/"
    # Check for updates every week
    schedule:
      interval: "weekly"
    reviewers:
      - "stroeer/teams/buzz-end"
